---
title: "Moments in US Constitutional Develoment"
author: "JBrandon Duck-Mayr"
# date: "`r quack::american_date_format(Sys.Date())`"
fontsize: 12pt
header-includes:
    - \usepackage{reading-fmts-cmds}
    - \definecolor{Blue}{RGB}{0, 95, 134}
    - \definecolor{Teal}{RGB}{0, 169, 183}
urlcolor: Blue
linkcolor: Teal
output: quack::article
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The U.S. Constitution as we've studied it so far has changed over the last 235 years, in some ways considerably so.
Sometimes changes to our constitutional order were brought about by amendments to the Constitution, but some were not.
We'll explore a few such changes and how they came to pass.

# 11th Amendment: Overruling the Court

In 1777, the state of Georgia purchased supplies for the Continental Army from Robert Farquhar.
However, Georgia had failed to pay for the supplies Farquhar delivered even by the time he died in 1784.
Alexander Chisholm was the executor of Farquhar's estate, and a citizen of South Carolina.[^1]
Chisolm sued the state of Georgia in federal court, seeking payment.
Initially the suit was dismissed for procedural reasons,[^2] so Chisholm refiled the suit directly at the Supreme Court, invoking the Court's original jurisdiction:

[^1]: State citizenship is based on residency, or more precisely, domicile.
[^2]: The lower court determined the Judiciary Act did not grant lower courts jurisdiction here.

\begin{quote}
\begin{center}
\textbf{Article III, \S\ 2}
\end{center}

The judicial power shall extend\dots\ to controversies\dots\ between a state and citizens of another state\dots

In all cases\dots\ in which a state shall be party, the Supreme Court shall have original jurisdiction.
\end{quote}

The Supreme Court, in an opinion by Chief Justice John Jay, held that Article III \S\ 2 means that the Supreme Court has original jurisdiction over any case between a state and a citizen of another state, including when the state is not the plaintiff.
This surprised and angered many, who argued the clause should be interpreted to give the Court jurisdiction only over cases where a state was suing a citizen of another state, and not the other way around.
Many saw the states as their own sovereign powers, meaning in part that they should enjoy sovereign immunity, a doctrine that limits the ability of people to sue the government.

Congress quickly passed the Eleventh Amendment, and the states quickly ratified it.
The amendment was designed, expressly, to undo the Supreme Court's decision in *Chisholm v. Georgia*.
While the Court has the last say in how a constitutional provision is interpreted, the People always have the power to amend the Constitution so that the provisions say something else, including if the People think the Court's interpretation needs to be corrected.

\begin{quote}
\begin{center}
\textbf{Eleventh Amendment to the U.S. Constitution}
\end{center}

The Judicial power of the United States shall not be construed to extend to any suit in law or equity, commenced or prosecuted against one of the United States by Citizens of another State, or by Citizens or Subjects of any Foreign State.
\end{quote}

After the ratification of the Eleventh Amendment, states could no longer be sued by citizens of other states in federal courts.
The Court has subsequently interpreted the Amendment to additionally prohibit states from being sued by their own citizens.
This affected the power of state governments, which is always an important development in the American constitutional order, but also significantly it was the first time Congress and the states have banded together to push back against the Supreme Court.
The Court has also been overruled by other constitutional amendments, briefly described below.

## Thirteenth & Fourteenth Amendments: *Dred Scott*

Dred Scott was born into slavery.
He was sold to a soldier in the US Army, who brought Scott with him as he was moved between postings, including spending several years in a free state.
Scott sued for his freedom, arguing he became free when residing in free states.
The Supreme Court ruled against Scott and held that any person descended from Africans were not US citizens.

As further described in Section \@ref(sec:reconstruction), the Thirteenth, Fourteenth, and Fifteenth Amendments were ratified after the Civil War as part of Reconstruction.
The Thirteenth and Fourteenth Amendments in particular overrule *Dred Scott*:

\begin{quoteblock}{Thirteenth Amendment to the US Constitution, \S\ 1}
Neither slavery nor involuntary servitude, except as a punishment for crime whereof the party shall have been duly convicted, shall exist within the United States, or any place subject to their jurisdiction.
\end{quoteblock}

\begin{quoteblock}{Fourteenth Amendment to the US Constitution, \S\ 1}
All persons born or naturalized in the United States, and subject to the jurisdiction thereof, are citizens of the United States and of the State wherein they reside\dots
\end{quoteblock}

## Sixteenth Amendment: *Pollock v. Farmers' Loan & Trust Co*

In 1894, Congress imposed, among other things, an income tax in the Wilson-Gorman Tariff Act.
Farmers' Loan & Trust Co announced it would comply with the act, and moreover give the government the names of all the people it was paying the income tax for.
Charles Pollock was a shareholder who sued to prevent the company from taking those actions.
The Supreme Court ruled the tax was unconstitutional, citing Article I \S\ 9, which reads in relevant part, "No capitation, or other direct, tax shall be laid, unless in proportion to the census or enumeration herein before directed to be taken."

About 10 years later, when debating another tax bill, Congress proposed the Sixteenth Amendment which would overrule *Pollock*.
Ratification by the states took almost five years, but eventually it was adopted.

\begin{quoteblock}{Sixteenth Amendment to the US Constitution}
The Congress shall have power to lay and collect taxes on incomes, from whatever source derived, without apportionment among the several States, and without regard to any census or enumeration.
\end{quoteblock}

## Nineteenth Amendment: *Minor v. Happersett*

Originally, women did not have the right to vote in the US.
Virginia Minor was a women's suffrage activist; she tried to register to vote in Saint Louis, Missouri in 1872, but was refused.
She sued the registrar who refused her, Reese Happersett.
She argued that the Fourteenth Amendment granted citizenship without respect to gender, and that the right to vote was a part of that citizenship.
The US Supreme Court held the right to vote was not guaranteed by the Fourteenth Amendment, so the states could restrict women's right to vote.

Women's suffrage advocates quickly called for a constitutional amendment guaranteeing women's right to vote.
In 1878, Senator Aaron Sargent introduced such an amendment in Congress, but it did not succeed.
Eventually Congress did pass an amendment in 1919 which was quickly ratified by the states.
The Nineteenth Amendment guaranteed the right to vote could not be denied on account of sex, explicitly overruling *Minor*.

\begin{quoteblock}{Nineteenth Amendment to the US Constitution}
The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of sex\dots
\end{quoteblock}

## Twenty Sixth Amendment: *Oregon v. Mitchell*

The Voting Rights Act of 1965 was designed to prevent racial discrimination in voting.
It was amended in 1970 to, among other things, expand the right to vote to citizens 18 years of age or older; previously the age was 21.
This was largely prompted by the Vietnam War and drafting of citizens who could not vote because they were too young.
The Supreme Court ruled this section of the Voting Rights Act was unconstitutional, noting several provisions protecting the right to vote for citizens with various characteristics (e.g. gender discrimination prohibited in the Nineteenth Amendment), implying that the right was not guaranteed based on any other restrictions.
The Twenty Sixth Amendment was quickly introduced in Congress and ratified by the states, explicitly overruling *Mitchell*.

\begin{quoteblock}{Twenty Sixth Amendment to the US Constitution \S\ 1}
The right of citizens of the United States, who are eighteen years of age or older, to vote shall not be denied or abridged by the United States or by any State on account of age.
\end{quoteblock}

# 12th Amendment: Electoral College Problems

Today, when the Electoral College meets, each elector casts a ballot for President and a ballot for Vice President, but Article II \S\ 1 originally had a different scheme.
Each elector in the Electoral College would cast two votes for president, with the requirement that one of those votes couldn't be for someone from the elector's own state.
The person with the most votes became President, if they had a majority of the votes; if not, the House of Representatives chooses between tied candidates if two candidates each get half of the votes, or from the top five candidates otherwise.
The person with the second most number of votes became Vice President.

In the 1796 presidential election, Federalist John Adams received a majority of votes in the Electoral College and thus was elected president.
However, the person with the second most number of votes was Democratic-Republican Thomas Jefferson.
As you might expect, a President of one party and a Vice President of the opposing party caused some friction.
An amendment to fix the issue was promptly proposed in Congress but was not adopted.

The election of 1800 was even worse.
The Democratic-Republicans won decisively, but the Democratic-Republican electors in the Electoral College *each* cast one ballot for Thomas Jefferson, who they wanted as president, and one ballot Aaron Burr, who they wanted as Vice President.
This resulted in a contingent election in the House of Representatives as described above, but it took **35** attempts before they reach a winner.
This finally spurred the Twelfth Amendment, which is lengthy, but it instituted the modern system of the electors voting for President and Vice President separately, avoiding these issues.

# Reconstruction: A Fundamentally New Constitutional Order (13th, 14th, 15th Amendments) {#sec:reconstruction}

For 60 years after the adoption of the Twelfth Amendment, the Constitution was not amended again, but multiple amendments were adopted in the wake of the Civil War.
The Thirteenth Amendment abolished slavery and was adopted in 1865, right before the war's end.
After the war, we had to wrestle with the issue of how to reintegrate the southern states back into the Union, a process called [Reconstruction](https://www.britannica.com/event/Reconstruction-United-States-history).
Exactly how this should be done had been debated since the war began.

President Lincoln was assassinated just days after the end of the Civil War, resulting in Andrew Johnson becoming president.
President Johnson oversaw an initial Reconstruction effort from 1865 to 1866 that was very lax on the southern states.
During this time, southern states adopted "Black Codes" restricting the rights of freedmen.
In 1866, Congress proposed the Fourteenth Amendment, which ensured citizenship, Due Process, and Equal Protection of the laws for all people, but Johnson used his influence in the states to impede its ratification.

The election of 1866 resulted in a decidedly less moderate Congress.
In 1867 and 1868, Congress passed Reconstruction Acts outlining what southern states had to do to be readmitted to the Union.
The Acts required southern states to, among other things, abolish the Black Codes and ratify the Fourteenth Amendment.
This led to the Fourteenth Amendment's ratification in 1868.
In 1870, we adopted the Fifteenth Amendment prohibited denying the right to vote based on race.
These amendments and the broader Reconstruction Effort they were a part of ushered in a fundamentally different constitutional order, abolishing slavery and prohibiting abridgment of rights based on race.

\begin{quoteblock}{Thirteenth Amendment to the US Constitution, \S\ 1}
Neither slavery nor involuntary servitude, except as a punishment for crime whereof the party shall have been duly convicted, shall exist within the United States, or any place subject to their jurisdiction.
\end{quoteblock}

\begin{quoteblock}{Fourteenth Amendment to the US Constitution, \S\ 1}
All persons born or naturalized in the United States, and subject to the jurisdiction thereof, are citizens of the United States and of the State wherein they reside. No State shall make or enforce any law which shall abridge the privileges or immunities of citizens of the United States; nor shall any State deprive any person of life, liberty, or property, without due process of law; nor deny to any person within its jurisdiction the equal protection of the laws.
\end{quoteblock}

\begin{quoteblock}{Fifteenth Amendment to the US Constitution, \S\ 1}
The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of race, color, or previous condition of servitude.
\end{quoteblock}

# New Deal: A New Economic Order

In response to [the Great Depression](https://www.britannica.com/event/Great-Depression), President Franklin Delano Roosevelt (typically called FDR) pushed the "New Deal" plan designed to help the economy recover and provide relief for the poor.
FDR got several bills passed by Congress that instituted new government programs and created new government agencies, all with the objective of improving the devastated economy and helping those struggling in it.
However, the Supreme Court repeatedly struck down those laws on various grounds, most commonly and most notably holding that Congress was impermissibly delegating too much authority to (these new) executive branch agencies and that some bills went farther than Congress' ability under the Constitution to regulate interstate commerce.

So, on February 9, 1937, FDR announced his federal court reorganization plan, which included a plan to "pack the Court", or add seats on the Supreme Court to give him the ability to appoint additional justices so he could obtain favorable outcomes at the Court.
It was initially unpopular, so on March 9, he made a direct appeal to the people via radio broadcast.
Twenty days later, the Court upheld Washington state wage and working condition regulations 5-4 in *West Coast Hotel v. Parrish* (1937), signaling a shift.
They continued ruling in favor of New Deal legislation, causing support for any court packing plan to wane.

The New Deal plan and the Supreme Court precedents that were built to uphold it represented an important shift in the American constitutional order.
The power of the federal government was *greatly* expanded, and the relationship between the Executive Branch and Congress was altered in an important way.
The Court's new interpretation of the Commerce Clause (the clause in Article I \S\ 8 that gives Congress the power to regulate interstate commerce) has been the source of most expansions of federal power since.
The Court's new interpretation of Congress' ability to delegate its power to others was essential to the creation of the federal bureaucracy.

# The Warren Court: Expansion of Rights

In 1953, President Dwight D. Eisenhower appointed California Governor Earl Warren to be Chief Justice of the US Supreme Court.
Warren had no experience as a judge, but he had previously served as District Attorney of Alameda County in California and as the Attorney General of California.
He was very active in Republican politics, chairing the Republican Part of California from 1932 to 1938; what he may or may not have lacked from having no judicial experience he made up for with political experience, having served as Governor of California for a decade.

This appointment led to one of the greatest periods of expansion of liberty in the US.
The Warren Court ended *de jure* segregation,[^3] applied liberties from the US Constitution against state governments like the Fourth Amendment freedom from unreasonable searches and seizures[^4] or the Sixth Amendment guarantee of assistance of counsel even if you can't afford a lawyer,[^5] and instituted the famous "*Miranda* warning".[^6]
The Warren Court gave us a right to privacy[^7] in *Griswold v. Connecticut*, 381 U.S. 479 (1965), a case about whether the government could prohibit a married couple from buying contraception.
In short, the Warren Court radically changed the relationship between government and the individual, a true shift to our constitutional order.

[^3]: *De jure* means "in law", as opposed to *de facto*, or "in (actual) fact".
      *Brown v. Board of Education* (1954) declared segregation unlawful, but considerable work was required over the next several years to make this a reality.
[^4]: *Mapp v. Ohio*, 367 U.S. 643 (1961) prohibits state courts from using evidence obtained in violation of the Fourth Amendment.
[^5]: Before *Gideon v. Wainwright*, 372 U.S. 335 (1963), the obligation of the government to pay for indigent defendants' lawyers only applied to federal cases.
[^6]: *Miranda v. Arizona*, 384 U.S. 436 (1966), held that "unless other fully effective means are devised to inform accused persons of their [rights]... Prior to any questioning, the person must be warned that he has a right to remain silent, that any statement he does make may be used as evidence against him, and that he has a right to the presence of an attorney, either retained or appointed. The defendant may waive... these rights, provided the waiver is made voluntarily, knowingly and intelligently."
[^7]: *Dobbs v. Jackson Women's Health Organization*, 597 U.S. 215 (2022), eliminated the federal right to abortion.
      Some argue its reasoning would additionally apply to *any* of the Court's privacy precedents, though this is so far untested.
