---
title: "The Executive: Fundamentals and Research"
author: "JBrandon Duck-Mayr"
# date: "`r quack::american_date_format(Sys.Date())`"
fontsize: 12pt
header-includes:
    - \usepackage{reading-fmts-cmds}
    - \definecolor{BurntOrange}{RGB}{191, 87, 0}
    - \definecolor{DarkGrey}{RGB}{51, 63, 72}
    - \definecolor{White}{RGB}{255, 255, 255}
    - \definecolor{LightOrange}{RGB}{248, 151, 31}
    - \definecolor{Gold}{RGB}{255, 214, 0}
    - \definecolor{LightGreen}{RGB}{166, 205, 87}
    - \definecolor{DarkGreen}{RGB}{87, 157, 66}
    - \definecolor{Teal}{RGB}{0, 169, 183}
    - \definecolor{Blue}{RGB}{0, 95, 134}
    - \definecolor{MidGrey}{RGB}{156, 173, 183}
    - \definecolor{LightGrey}{RGB}{214, 210, 196}
    - \definecolor{Purple}{RGB}{110, 50, 120}
    - \definecolor{SoftPurple}{HTML}{af87af}
    # - \definecolor{CustomGreen}{RGB}{55, 120, 18}
    # - \definecolor{CustomGreen}{RGB}{44, 120, 33}
    - \usepackage{sidebar}
urlcolor: Blue
linkcolor: SoftPurple
output: quack::article
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Last unit, we started to discuss the powers of the executive.
Now we'll flesh out the structure and power of the executive.
After laying those constitutional foundations, you'll be introduced to some modern political science research on The Executive.

# Executive Branch Structure & Executive Power

The Constitution does not give much detail as to the structure of the executive branch.
We know there will be a President and Vice President (Article II \S\ 1).
We also know the Framers had in mind some structure of "executive departments" (Article II \S\ 2).
But that's it. As with the judiciary, Congress is largely the one that fills out the details.

\begin{sidebar}[Blue]{Article II of the US Constitution (emphasis added)}
\S 1 (Vesting Clause): The executive power shall be vested in \textbf{\textcolor{BurntOrange}{a President of the United States of America}}. He shall hold his office during the term of four years\dots\ together with \textbf{\textcolor{Blue}{the Vice President}}

\S 2: The President\dots\ may require the opinion, in writing, of \textbf{\textcolor{Purple}{the principal officer in each of the executive departments}}, upon any subject relating to the duties of their respective offices\dots
\end{sidebar}

\begin{quoteblock}{An act to establish... the Department of war. 1789\footnote{Full text at \url{https://www.loc.gov/item/2020767848/}}}

An ACT to establish an Executive Department to be denominated the Department of War.

BE IT ENACTED by the Senate Congress of the United States, That there shall be an Executive Department, to be denominated, “The Department of War,” and that there shall be a principal officer therein, to be called the Secretary for the Department of War, and who shall perform and execute such duties as shall... be... intrusted to him, by the President of the United States, agreeably to the Constitution, relative to... matters respecting military or naval affairs, as the President of the United States shall assign to the said department... And furthermore, That the said principal officer shall conduct the business of the said department, in such manner as the President of the United States shall, from time to time, order or instruct.

And be it further enacted, That there shall be in the said department, an inferior officer, to be
appointed by the said principal officer, to be employed therein as he shall deem proper... and who, whenever the said principal officer shall be removed from office by the President of the United States, or in any other case of vacancy, shall during such vacancy, have the charge and custody of all records, books and papers, appertaining to the said department...

1789, June 27.
\end{quoteblock}

Very quickly, the first US Congress passed laws creating the Foreign Affairs Department (now Department of State), the War Department (now the Department of Defense), and the treasury department.
Over time, Congress began adding executive departments\footnote{Such as the Department of Agriculture, Department of Energy, Department of Education\dots} to help the President "take care that the laws be faithfully executed" (Article II \S\ 3, also called the "Take Care Clause").\footnote{Note that Congress' power to create executive agencies is an implied power.}
More details about these departments will be discussed in class, but in short the structure of the Executive Branch is the President at the top, the Vice President and the heads of executive departments underneath the President, and agency personnel below that.

The Executive Power can cover a range of things, and there has historically been debate about what the phrase means.

\begin{quoteblock}{In Re Neagle (1890)\footnote{Full text at \url{https://supreme.justia.com/cases/federal/us/135/1/}}}
[At this time, appellate court panels included one Supreme Court justice. Each justice was assigned to one appellate ``circuit" (justices traveled in a circuitous path for this purpose). A death threat caused the President to appoint a US Marshal to protect the justice, though Congress passed no law authorizing that. Marshal Neagle killed the assassin and was charged with murder by California. A federal court granted Neagle a write of \textit{habeas corpus}, and California appealed.]

\dots Mr. Justice Field, when attacked, was in the immediate discharge of his duty as judge of the Circuit Courts of the United States within California\dots\ and that the deputy marshal\dots\ was charged with a duty under the law of the United States to protect Field from\dots\ violence\dots\ which was intended to lead to Field's death\dots

Mr. Justice Field was a member of the Supreme Court\dots\ for over a quarter of a century\dots\ he had become venerable for\dots\ his long and valuable service\dots\ The business of the Supreme Court has become so exacting\dots\ The term for each year, including\dots\ travel and preparations\dots\ has generally lasted from eight to nine months.

But the justices of this court have\dots\ other duties\dots\

So\dots\ a justice\dots\ is compelled\dots\ to [sit] on the Circuit Courts\dots\

We have no doubt\dots\ Justice Field, when attacked\dots\ was engaged in the discharge of his duties\dots\ and was entitled to\dots\ protection\dots\

[California urges] there [is] no statute authorizing\dots\ protection\dots

In [our view] of the Constitution\dots\ any obligation\dots\ or any duty\dots\ derived from the general scope of his duties under the laws of the United States, is "a law" within the meaning of this phrase\dots

Where\dots\ are we to look for the protection which we have shown Judge Field was entitled to\dots? Not to the courts\dots\ [Officers who execute courts' judgments] are marshals\dots\ and belong emphatically to the executive department of the government. They are appointed by the President, with the advice and consent of the Senate. They are removable from office at his pleasure\dots

The legislative branch\dots\ can only protect the judicial officers by the enactment of laws\dots\ and the argument we are now combating assumes that no such law has been passed by Congress.

If we turn to the executive\dots\ The Constitution\dots\ declares that the President "shall take care that the laws be faithfully executed," and he is provided with the means of [doing so] by his authority to [appoint executive officers]\dots\ The duties which are thus imposed upon him he is further enabled to perform by\dots\ the creation by acts of Congress, of executive departments, which have varied in number from four or five to seven or eight\dots\ thus he is enabled to fulfill the duty of his great department, expressed in the phrase that "he shall take care that the laws be faithfully executed"\dots

That there is a peace of the United States, that a man assaulting a judge of the United States while in the discharge of his duties violates that peace, that, in such case, the marshal of the United States stands in the same relation to the peace of the United States which the sheriff of the county does to the peace of the State of California, are questions too clear to need argument to prove them\dots

We have thus given, in this case, a most attentive consideration to all the questions of law and fact which we have thought to be properly involved in it\dots\ The result\dots\ is that, in the protection of the person and the life of Mr. Justice Field while in the discharge of his official duties,
Neagle was authorized to resist the attack\dots\ [so] he was acting under the authority of the law of the United States, and was justified in so doing; and that he is not liable to answer in the courts of California on account of his part in that transaction.

We therefore affirm the judgment of the circuit court authorizing his discharge from the custody of the sheriff of San Joaquin county.
\end{quoteblock}

\begin{sidebar}[Blue]{In re Neagle}
The Constitution\dots\ declares that the President "shall take care that the laws be faithfully executed," and he is provided with the means of fulfilling this obligation by his authority to [appoint executive officers]\dots\ The duties which are thus imposed upon him he is further enabled to perform by\dots\ the creation by acts of Congress, of executive departments, which have varied in number from four or five to seven or eight\dots\ thus he is enabled to fulfill the duty of his great department, expressed in the phrase that "he shall take care that the laws be faithfully executed"\dots
\end{sidebar}

In addition to the power implied by the Vesting Clause and the Take Care Clause, there are specific powers of the presidency granted in the text of the Constitution. From Article II \S\ 2:

- Commander in Chief of the military
- Demand reports from executive agencies
- Power to pardon (federal crimes only)
- Make treaties (if ratified by 2/3 of the Senate)
- Appoint ambassadors, federal judges and justices, and other officers (if ratified by 50% of the Senate + 1)
- Make recess appointments without needing a Senate vote

From Article II \S\ 3:

- State of the Union speech
- Convene Congress in an emergency
- Receive ambassadors (also implying the power to recognize foreign states, or not)
- "take Care that the laws be faithfully executed"
- Commission all officers of the US

# Modern Research

Political science research on the executive covers a wide range of topics and uses a variety of methods.
An important branch of research uses game theory to study how presidents exercise power unilaterally (e.g. [Howell 2003](https://doi.org/10.1515/9781400874392)).
The president's control over the bureaucracy, their role as a party leader, and presidents in the electoral context are all significant topics.
There is also some debate about who presidents serve...

\begin{center}
\href{https://www.jstor.org/stable/43655030}{\textrm{Presidential Particularism and Divide-the-Dollar Politics}}

\textit{by Douglas L. Kriner and Andrew Reeves}
\end{center}

In articulating his stewardship theory of presidential power, Theodore Roosevelt emphasized that the president's national constituency rendered the office uniquely positioned in the American political system to pursue the interests of the nation as a whole. Woodrow Wilson echoed this view. Contrasting members of Congress who are "representatives of localities" and who are "voted for only by sections of voters" with presidents who are elected by the nation, Wilson concluded that the president "is the representative of no constituency, but of the whole people." When the president "speaks in his true character, he speaks for no special interest. If he rightly interprets the national thought and boldly insists upon it, he is irresistible" (Wilson 1908, 67–8).

A century later, many scholars and pundits alike continue to embrace Roosevelt’s and Wilson’s contrast between congressional parochialism and presidential universalism...

Others acknowledge that presidents, like members of Congress, pursue their political interests, such as reelection, but contend that the president’s national constituency incentivizes universalism...

For example, game theoretic research by Howell, Jackman, and Rogowski (2013) posits that "presidents focus on the national implications of public policies while members of Congress monitor the effects of public policy on both the nation as a whole and their local constituencies."

We argue that while the universalistic framework undoubtedly captures important differences between presidents and legislators, it misconstrues the forces driving presidential behavior. We argue that presidents face strong incentives to be particularistic: that is to prioritize the needs and desires of some citizens over others when pursuing their policy agendas. We test the explanatory power of universalism versus particularism in the context of divide-the-dollar politics. Universalism suggests that presidents will pursue budgetary policies that allocate federal spending to constituencies in a manner that is unrelated to their political characteristics; maximum efficiency and appealing to the national median voter is the president’s primary objective.

Conversely, particularistic presidents geographically target federal spending to serve a number of ends. To maximize their prospects of reelection, presidents do not simply pursue nationally optimal outcomes or follow the preferences of the national median voter, as much universalistic scholarship argues. While the president has a national constituency, not all voters have equal influence in presidential elections; therefore presidents have incentives to respond disproportionately to the interests of Americans in constituencies with the most clout in the next presidential contest. Presidents also diverge from the norms of universalism to serve other goals. Building on research emphasizing the president's role as a partisan leader [numerous citations omitted], we show that presidents systematically reward constituencies that reliably vote for them and their party with disproportionate shares of federal largesse. Moreover, as Berry, Burden, and Howell (Reference Berry, Burden and Howell2010) argues, presidents can also strategically allocate funds to gain leverage vis-à-vis co-partisan members of the legislature. In stark contrast to the universalistic paradigm, which paints a picture of presidents providing a counterbalance to congressional parochial impulses, we reveal substantial presidentially induced inequalities favoring politically significant constituencies...

\begin{center}
Data and Methods
\end{center}

To what extent do presidents influence the distribution of federal grants across geographic constituencies in the United States? To answer this question, we follow Berry, Burden, and Howell (2010) and Kriner and Reeves (2012) and compile data from the Consolidated Federal Funds Report (CFFR) on every federal grant program from 1984 to 2008. For each program, the CFFR reports the amount of money spent in each county in a given year...

If presidents do indeed strictly pursue the national interest and maximally efficient policy outcomes, then the share of federal grant dollars that a county receives should be unrelated to its political characteristics. However, if electoral, partisan, and coalition incentives encourage presidents to deviate from the norms of universalism, then presidents should seek to target federal dollars to politically valuable constituencies...

\begin{center}
Results
\end{center}

...we find strong evidence of presidential particularism with support for our swing state, core state, and co-partisan congressional hypotheses. The coefficients for these variables are all positive and statistically significant. These findings are inconsistent with the universalistic presidency model, which contends that the allocation of federal funds should not be related to political variables. Even in budgetary policymaking—a context where the president’s authority is checked by many other actors—we see strong evidence of presidential particularism as constituencies of greater political importance to the president secure significantly greater shares of federal dollars than other constituencies. These relationships are robust across multiple specifications...
